# Generated by Django 5.1.5 on 2025-02-03 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponic_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydroponicsystem',
            options={'verbose_name': 'HydroponicSystem', 'verbose_name_plural': 'HydroponicSystems'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hydroponicsystem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ph',
            field=models.FloatField(verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='hydroponic_api.hydroponicsystem', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='tds',
            field=models.FloatField(verbose_name='tds'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
